spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml